### ISSUE TITLE
Missing source for SharedCoreLib

### ISSUE THREAD

**Issue by useretail** [tomer8007/windows-shazam#1]
Hi, thanks for sharing, but where is the source for SharedCoreLib?

**Comment by tomer8007** [comment]
Well, unfortunately `SharedCoreLib.dll` was taken from Shazam's official app for Windows 8 and so its original source code is not available.
-BUT-
The file was not obfuscated at all, meaning that by using .NET decompilers such as [dotPeek](https://www.jetbrains.com/decompiler/) you can easily read and understand its content. I gave it a shot and it was actually pretty easy to understand (you basically get the source code back).

**Comment by useretail** [comment]
Ok, thanks for clarification. Next step - Linux client.
